<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="1" errors="1" failures="0" skip="0"><testcase classname="user_test.TestAccount" name="test_account_init" time="0.002"><error type="builtins.AttributeError" message="'TestAccount' object has no attribute 'new_account'"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/jerome/python_flask/user_test.py", line 57, in test_account_init
    self.assertEqual(self.new_account.account,"Gmail")
AttributeError: 'TestAccount' object has no attribute 'new_account'
]]></error></testcase></testsuite>